// <auto-generated />
using System;
using BettingSportsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BettingSportsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507155249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BettingSportsApi.Models.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Odds")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Payout")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("BettingSportsApi.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AwayOdds")
                        .HasColumnType("REAL");

                    b.Property<int>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("DrawOdds")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeOdds")
                        .HasColumnType("REAL");

                    b.Property<int>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayOdds = 3.2000000000000002,
                            AwayScore = 0,
                            AwayTeam = "Бавария",
                            DrawOdds = 3.5,
                            HomeOdds = 2.1000000000000001,
                            HomeScore = 0,
                            HomeTeam = "ПСЖ",
                            IsCompleted = false,
                            League = "Champions League",
                            MatchDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AwayOdds = 4.0,
                            AwayScore = 0,
                            AwayTeam = "Атлетико Мадрид",
                            DrawOdds = 3.6000000000000001,
                            HomeOdds = 1.8,
                            HomeScore = 0,
                            HomeTeam = "Арсенал",
                            IsCompleted = false,
                            League = "Champions League",
                            MatchDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AwayOdds = 2.8999999999999999,
                            AwayScore = 0,
                            AwayTeam = "Арсенал",
                            DrawOdds = 3.3999999999999999,
                            HomeOdds = 2.2999999999999998,
                            HomeScore = 0,
                            HomeTeam = "Спортинг",
                            IsCompleted = false,
                            League = "Champions League",
                            MatchDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AwayOdds = 3.1000000000000001,
                            AwayScore = 0,
                            AwayTeam = "Ливерпуль",
                            DrawOdds = 3.2999999999999998,
                            HomeOdds = 2.2000000000000002,
                            HomeScore = 0,
                            HomeTeam = "Галатасарай",
                            IsCompleted = false,
                            League = "Champions League",
                            MatchDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AwayOdds = 3.7999999999999998,
                            AwayScore = 0,
                            AwayTeam = "Осасуна",
                            DrawOdds = 3.3999999999999999,
                            HomeOdds = 1.95,
                            HomeScore = 0,
                            HomeTeam = "Леванте",
                            IsCompleted = false,
                            League = "La Liga",
                            MatchDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AwayOdds = 4.5,
                            AwayScore = 0,
                            AwayTeam = "Сельта",
                            DrawOdds = 3.7000000000000002,
                            HomeOdds = 1.75,
                            HomeScore = 0,
                            HomeTeam = "Атлетико",
                            IsCompleted = false,
                            League = "La Liga",
                            MatchDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AwayOdds = 2.7999999999999998,
                            AwayScore = 0,
                            AwayTeam = "Бетис",
                            DrawOdds = 3.2000000000000002,
                            HomeOdds = 2.3999999999999999,
                            HomeScore = 0,
                            HomeTeam = "Реал Сосьедад",
                            IsCompleted = false,
                            League = "La Liga",
                            MatchDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AwayOdds = 2.6000000000000001,
                            AwayScore = 0,
                            AwayTeam = "Вильярреал",
                            DrawOdds = 3.1000000000000001,
                            HomeOdds = 2.6000000000000001,
                            HomeScore = 0,
                            HomeTeam = "Мальорка",
                            IsCompleted = false,
                            League = "La Liga",
                            MatchDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BettingSportsApi.Models.UserState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 10000m,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
